### ISSUE TITLE
cannot build/install dxfeed 0.5.2 on python 3.9.5/3.9.6

### ISSUE THREAD

**Issue by tdudz** [dxFeed/dxfeed-python-api#37]
**Describe the bug**
 - the `dxfeed` wheel will not build/install on python `3.9.5` or `3.9.6`

**To Reproduce**
 - run `pip install dxfeed` in a fresh python `3.9.5/6` environment

**Environment:**
 - OS: macOS
 - Python version: both 3.9.5 and 3.9.6
 - Package version: 0.5.2

**Additional context**
it works fine for us on python `3.8.10`. i tried this from a fresh, brand new python venv

output log, truncated because too long. seems to be some issue with clang/cython

```
  8 warnings generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DMACOSX=TRUE -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/include -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/include -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src -c /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/EventData.c -o /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/build/temp.macosx-11-x86_64-3.9/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/EventData.o
  In file included from /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/EventData.c:21:
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/DXAlgorithms.h:565:2: warning: "no fence, no atomic read/write for 64 bit variables on 32 bit platforms, additional synchronization is needed"; [-W#warnings]
  #warning "no fence, no atomic read/write for 64 bit variables on 32 bit platforms, additional synchronization is needed";
   ^
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/EventData.c:354:10: warning: enumeration values 'dx_eid_count' and 'dx_eid_invalid' not handled in switch [-Wswitch]
          switch (event_id) {
                  ^
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/EventData.c:354:10: note: add missing switch cases
          switch (event_id) {
                  ^
  2 warnings generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DMACOSX=TRUE -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/include -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/include -I/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src -c /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c -o /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/build/temp.macosx-11-x86_64-3.9/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.o
  In file included from /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c:23:
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/DXAlgorithms.h:565:2: warning: "no fence, no atomic read/write for 64 bit variables on 32 bit platforms, additional synchronization is needed"; [-W#warnings]
  #warning "no fence, no atomic read/write for 64 bit variables on 32 bit platforms, additional synchronization is needed";
   ^
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c:231:7: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                  if (memcmp(&dst[didx], &best, sizeof(best)) != 0) {
                      ^
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c:231:7: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c:338:6: warning: unused variable 'i' [-Wunused-variable]
          int i = 0;
              ^
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c:426:30: warning: unused variable 'context' [-Wunused-variable]
          dx_rb_connection_context_t *context = CTX(b->context);
                                      ^
  /private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/dxfeed/dxfeed-c-api/src/RegionalBook.c:457:30: warning: unused variable 'context' [-Wunused-variable]
          dx_rb_connection_context_t *context = CTX(b->context);
                                      ^
  4 warnings and 1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-build-env-4idzu3_v/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-build-env-4idzu3_v/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 72, in make_in
      wb.build()
    File "/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-build-env-4idzu3_v/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 103, in build
      self._build(zip_file)
    File "/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-build-env-4idzu3_v/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 135, in _build
      self._run_build_command(setup)
    File "/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-build-env-4idzu3_v/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 163, in _run_build_command
      subprocess.check_call(
    File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/Cellar/python@3.9/3.9.6/bin/python3.9', '/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/setup.py', 'build', '-b', '/private/var/folders/zv/__kt_qmj0svftpx157jmd7tm0000gn/T/pip-install-s0oigf3y/dxfeed_35165e4506914f19bb7b730e266477f5/build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dxfeed
```

**Comment by alimantu** [comment]
Hi @tdudz!

Issue should be resolved in our new release. Please check it out 😉
