### ISSUE TITLE
cannot import name 'DXFeedPy' from 'dxfeed.core'

### ISSUE THREAD

**Issue by wbwatkinson** [dxFeed/dxfeed-python-api#50]
**Describe the bug**
 - Attempting a very basic test of the dxfeed api results in an error when attempting to import DXFeePy from dxfeed.core

**To Reproduce**
 - I created a very basic file with only the following import statements:
```python
import dxfeed as dx
from datetime import datetime  # for timed subscription
```

**Behavior**
Full trace:
```bash
Traceback (most recent call last):
  File "~/dxfeed-python-api/tastytrade_sdk_demo.py", line 1, in <module>
    import dxfeed as dx
  File "~/dxfeed-python-api/dxfeed/__init__.py", line 1, in <module>
    from dxfeed.wrappers.endpoint import Endpoint
  File "~/dxfeed-python-api/dxfeed/wrappers/endpoint.py", line 1, in <module>
    from dxfeed.core import DXFeedPy as dxp
ImportError: cannot import name 'DXFeedPy' from 'dxfeed.core' (~/dxfeed-python-api/dxfeed/core/__init__.py)
```

**Expected behavior**
 - I expected all modules to be imported without error

**Environment:**
 - OS: MacOS 14.4.1
 - Python version: 3.9.16 (also fails with 3.10.11 and 3.11.3)
 - Package version: 0.5.3 (via git repository -- running `poetry install` on tar.gz file resulted in compilation errors)

Note: to get package version run `import pkg_resources; pkg_resources.get_distribution('dxfeed').version`

**Additional context**

**Comment by Mahmoud-Elbahnasawy** [comment]
The same here.
